apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-shredder
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-shredder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-shredder
subjects:
  - kind: ServiceAccount
    name: k8s-shredder
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-shredder
rules:
  - apiGroups: ["*"]
    resources: [nodes]
    verbs: [get, list, watch, update, patch]
  - apiGroups: ["*"]
    resources: [pods, pods/eviction]
    verbs: ["*"]
  - apiGroups: [apps, extensions]
    resources: [statefulsets, deployments, replicasets]
    verbs: [get, list, watch, update, patch]
  - apiGroups: [ "argoproj.io" ]
    resources: [ rollouts ]
    verbs: [ get, list, watch, update, patch ]
  - apiGroups: [ "karpenter.sh" ]
    resources: [ nodeclaims ]
    verbs: [ get, list, watch ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edit-debug-flags-v
rules:
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - update
- nonResourceURLs:
  - /debug/flags/v
  verbs:
  - put
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edit-debug-flags-v
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit-debug-flags-v
subjects:
- kind: ServiceAccount
  name: default
  namespace: default