apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-shredder.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "k8s-shredder.labels" . | indent 4 }}
data:
  config.yaml: |-
    EvictionLoopInterval: "{{.Values.shredder.EvictionLoopInterval}}"
    ParkedNodeTTL: "{{.Values.shredder.ParkedNodeTTL}}"
    RollingRestartThreshold: "{{.Values.shredder.RollingRestartThreshold}}"
    UpgradeStatusLabel: "{{.Values.shredder.UpgradeStatusLabel}}"
    ExpiresOnLabel: "{{.Values.shredder.ExpiresOnLabel}}"
    NamespacePrefixSkipInitialEviction: "{{.Values.shredder.NamespacePrefixSkipInitialEviction}}"
    RestartedAtAnnotation: "{{.Values.shredder.RestartedAtAnnotation}}"
    AllowEvictionLabel: "{{.Values.shredder.AllowEvictionLabel}}"
    ToBeDeletedTaint: "{{.Values.shredder.ToBeDeletedTaint}}"
    ArgoRolloutsAPIVersion: "{{.Values.shredder.ArgoRolloutsAPIVersion}}"
    EnableKarpenterDriftDetection: {{.Values.shredder.EnableKarpenterDriftDetection}}
    EnableKarpenterDisruptionDetection: {{.Values.shredder.EnableKarpenterDisruptionDetection}}
    ParkedByLabel: "{{.Values.shredder.ParkedByLabel}}"
    ParkedByValue: "{{.Values.shredder.ParkedByValue}}"
    ParkedNodeTaint: "{{.Values.shredder.ParkedNodeTaint}}"
    EnableNodeLabelDetection: {{.Values.shredder.EnableNodeLabelDetection}}
    NodeLabelsToDetect: {{.Values.shredder.NodeLabelsToDetect | toJson}}
    MaxParkedNodes: {{.Values.shredder.MaxParkedNodes}}
    EvictionSafetyCheck: {{.Values.shredder.EvictionSafetyCheck}}
    ParkingReasonLabel: "{{.Values.shredder.ParkingReasonLabel}}"
    ExtraParkingLabels: {{.Values.shredder.ExtraParkingLabels | toJson}}
