name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -quiet -exclude=G107 ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          # version: v1.46
           args: -v --timeout 5m --no-config ./...
      - name: Install k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          install_only: true
          version: v0.14.0
      - name: Prepare test environment
        run: make local-test
      - name: Run e2e tests
        run: make e2e-tests
